# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 10 Oct 2016 18:08:20 +0000
*               @ALL          1
*               @user         8
